In [1]:
#7.1
import numpy as np
np.ones((2,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [2]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [4]:
#7.2
np.arange(0,4)
np.arange(0,4) + 7
np.arange(0,4) *2

array([0, 2, 4, 6])

In [5]:
#7.3
Array1 = np.arange(2,20,2).reshape(3,3)
Array2 = np.arange(9, 0, -1).reshape(3,3)
Array1 * Array2

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

In [6]:
#7.4
List1=[2,3,5,7,11]
List2=[13,17,19,23,29]
np.vstack((List1, List2))

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])

In [7]:
#7.5
Array3 = np.array([1,0,4,8,32,64]).reshape(2,3)
Array3.flatten()
Array3
Array3.ravel()
Array3

array([[ 1,  0,  4],
       [ 8, 32, 64]])

In [10]:
#7.9
Array4 = np.arange(1,16).reshape(3,5)
Array4[2]
Array4[:, 4:5]
Array4[0:2]
Array4[:,2:4]
Array4[1,4]
Array4[1:3, [0,2,4]]

array([[ 6,  8, 10],
       [11, 13, 15]])

In [ ]:
#7.10
import os    
import time    
    
board = [' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']    
player = 1    
   
########win Flags##########    
Win = 1    
Draw = -1    
Running = 0    
Stop = 1    
###########################    
Game = Running    
Mark = 'X'    
   
#This Function Draws Game Board    
def DrawBoard():    
    print(" %c | %c | %c " % (board[1],board[2],board[3]))    
    print("___|___|___")    
    print(" %c | %c | %c " % (board[4],board[5],board[6]))    
    print("___|___|___")    
    print(" %c | %c | %c " % (board[7],board[8],board[9]))    
    print("   |   |   ")    
   
#This Function Checks position is empty or not    
def CheckPosition(x):    
    if(board[x] == ' '):    
        return True    
    else:    
        return False    
   
#This Function Checks player has won or not    
def CheckWin():    
    global Game    
    #Horizontal winning condition    
    if(board[1] == board[2] and board[2] == board[3] and board[1] != ' '):    
        Game = Win    
    elif(board[4] == board[5] and board[5] == board[6] and board[4] != ' '):    
        Game = Win    
    elif(board[7] == board[8] and board[8] == board[9] and board[7] != ' '):    
        Game = Win    
    #Vertical Winning Condition    
    elif(board[1] == board[4] and board[4] == board[7] and board[1] != ' '):    
        Game = Win    
    elif(board[2] == board[5] and board[5] == board[8] and board[2] != ' '):    
        Game = Win    
    elif(board[3] == board[6] and board[6] == board[9] and board[3] != ' '):    
        Game=Win    
    #Diagonal Winning Condition    
    elif(board[1] == board[5] and board[5] == board[9] and board[5] != ' '):    
        Game = Win    
    elif(board[3] == board[5] and board[5] == board[7] and board[5] != ' '):    
        Game=Win    
    #Match Tie or Draw Condition    
    elif(board[1]!=' ' and board[2]!=' ' and board[3]!=' ' and board[4]!=' ' and board[5]!=' ' and board[6]!=' ' and board[7]!=' ' and board[8]!=' ' and board[9]!=' '):    
        Game=Draw    
    else:            
        Game=Running    
    
print("Tic-Tac-Toe Game Designed By Sourabh Somani")    
print("Player 1 [X] --- Player 2 [O]\n")    
print()    
print()    
print("Please Wait...")    
time.sleep(3)    
while(Game == Running):    
    os.system('cls')    
    DrawBoard()    
    if(player % 2 != 0):    
        print("Player 1's chance")    
        Mark = 'X'    
    else:    
        print("Player 2's chance")    
        Mark = 'O'    
    choice = int(input("Enter the position between [1-9] where you want to mark : "))    
    if(CheckPosition(choice)):    
        board[choice] = Mark    
        player+=1    
        CheckWin()    
    
os.system('cls')    
DrawBoard()    
if(Game==Draw):    
    print("Game Draw")    
elif(Game==Win):    
    player-=1    
    if(player%2!=0):    
        print("Player 1 Won")    
    else:    
        print("Player 2 Won")    

Tic-Tac-Toe Game Designed By Sourabh Somani
Player 1 [X] --- Player 2 [O]



Please Wait...
   |   |   
___|___|___
   |   |   
___|___|___
   |   |   
   |   |   
Player 1's chance


In [ ]:
#7.14

